# Welcome to Serverless!
#
# For full config options, check out the Alibaba Cloud Function Compute
# plugin docs:
#    https://github.com/aliyun/serverless-aliyun-function-compute
#
# For documentation on Alibaba Cloud Function Compute itself:
#    https://serverless.aliyun.com

# Update the service name below with your own service name

service: health_check

frameworkVersion: '3'

provider:
  name: aliyun
  region: cn-hangzhou
  runtime: nodejs12
  credentials: ~/.aliyuncli/credentials
  timeout: 150

plugins:
  - serverless-aliyun-function-compute

package:
  exclude:
    - package-lock.json
    - .gitignore
    - .git/**

functions:
  check:
    handler: index.check
