name: mainWorkFlow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Build Blog
      run: |
        npm install -g serverless
        serverless plugin install --name serverless-aliyun-function-compute
        npm install
    - name: config credentials
      run: |
        mkdir ~/.aliyuncli
        touch ~/.aliyuncli/credentials
        echo "[default]" > ~/.aliyuncli/credentials
        echo "aliyun_access_key_secret = ${{ secrets.ACCESS_KEY_SECRET }}" > ~/.aliyuncli/credentials
        echo "aliyun_access_key_id = ${{ secrets.ACCESS_KEY_ID }}" > ~/.aliyuncli/credentials
        echo "aliyun_account_id = ${{secrets.ACCOUNT_ID}}" > ~/.aliyuncli/credentials
    - name: Deploy
      run: |
        serverless deploy
    - name: Invoke
      run: serverless invoke --function first

    